-- MySQL Script generated by MySQL Workbench
-- Tue Oct 17 21:43:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `tipo_documento` VARCHAR(5) NULL,
  `num_documento` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tipo_membresia` VARCHAR(45) NULL,
  `plan_membresia` VARCHAR(45) NULL,
  `fecha_inscripcion` DATE NULL,
  `fecha_vencimiento` DATE NULL,
  `estado_pago` VARCHAR(45) NULL,
  `peso` FLOAT NULL,
  `altura` FLOAT NULL,
  `porcentaje_grasa` FLOAT NULL,
  `fecha_revision` DATE NULL,
  `fecha_prox_revision` DATE NULL,
  `restricciones_medicas` VARCHAR(255) NULL,
  `notas_adicionales` VARCHAR(255) NULL,
  PRIMARY KEY (`num_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefonos_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefonos_Cliente` (
  `num_documento` INT NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`num_documento`),
  CONSTRAINT `fk_Telefono_1`
    FOREIGN KEY (`num_documento`)
    REFERENCES `mydb`.`Cliente` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas` (
  `nombre` VARCHAR(25) NULL,
  `ID` INT NOT NULL,
  `ubicacion` VARCHAR(45) NULL,
  `equipamiento` VARCHAR(45) NULL,
  `capacidad` INT NULL,
  `horario_inicio_funcionamiento` DATETIME NULL,
  `horario_fin_funcionamiento` DATETIME NULL,
  `instructores` VARCHAR(45) NULL,
  `clases` VARCHAR(45) NULL,
  `nivel_acceso` INT NULL,
  `estado` VARCHAR(25) NULL,
  `fecha_ultimo_mantenimiento` DATE NULL,
  `fecha_prox_mantenimiento` DATE NULL,
  `comentarios` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `C.C` INT NULL,
  `ID_empleado` INT NOT NULL,
  `primer_nombre` VARCHAR(45) NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `primer_apellido` VARCHAR(45) NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fecha_contratacion` DATE NULL,
  `num_segurosocial` INT NULL,
  `horario_inicio_trabajo` DATETIME NULL,
  `horario_fin_trabajo` DATETIME NULL,
  `salario` FLOAT NULL,
  `certificados` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono_Empleado` (
  `ID_empleado` INT NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_empleado`),
  CONSTRAINT `fk_Telefono_Empleado_1`
    FOREIGN KEY (`ID_empleado`)
    REFERENCES `mydb`.`Empleados` (`ID_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accesorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accesorio` (
  `ID` INT NOT NULL,
  `tipo_equipo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `num_serie` INT NULL,
  `fecha_adquisicion` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `fecha_ultimo_mantenimiento` DATE NULL,
  `fecha_prox_mantenimiento` DATE NULL,
  `ubicacion` VARCHAR(45) NULL,
  `fecha_retirada` DATE NULL,
  `con_fisica` VARCHAR(45) NULL,
  `comentarios` VARCHAR(45) NULL,
  `num_documento` INT NULL,
  `ID_zona` INT NULL,
  `ID_empleado` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Accesorio_1_idx` (`num_documento` ASC) VISIBLE,
  INDEX `fk_zona_2_idx` (`ID_zona` ASC) VISIBLE,
  INDEX `fk_empleado_1_idx` (`ID_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_1`
    FOREIGN KEY (`num_documento`)
    REFERENCES `mydb`.`Cliente` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zona_2`
    FOREIGN KEY (`ID_zona`)
    REFERENCES `mydb`.`Zonas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_1`
    FOREIGN KEY (`ID_empleado`)
    REFERENCES `mydb`.`Empleados` (`ID_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_Zona` (
  `num_documento` INT NOT NULL,
  `ID` INT NOT NULL,
  PRIMARY KEY (`num_documento`, `ID`),
  INDEX `fk_Zona_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente`
    FOREIGN KEY (`num_documento`)
    REFERENCES `mydb`.`Cliente` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zona`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Zonas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado_Cliente` (
  `ID_empleado` INT NOT NULL,
  `num_documento` INT NOT NULL,
  PRIMARY KEY (`ID_empleado`, `num_documento`),
  INDEX `fk_Empleado_Cliente_2_idx` (`num_documento` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Cliente_1`
    FOREIGN KEY (`ID_empleado`)
    REFERENCES `mydb`.`Empleados` (`ID_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Cliente_2`
    FOREIGN KEY (`num_documento`)
    REFERENCES `mydb`.`Cliente` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado_Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado_Zona` (
  `ID_empleado` INT NOT NULL,
  `ID_zona` INT NOT NULL,
  PRIMARY KEY (`ID_empleado`, `ID_zona`),
  INDEX `fk_Empleado_Zona_2_idx` (`ID_zona` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Zona_1`
    FOREIGN KEY (`ID_empleado`)
    REFERENCES `mydb`.`Empleados` (`ID_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Zona_2`
    FOREIGN KEY (`ID_zona`)
    REFERENCES `mydb`.`Zonas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrenadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrenadores` (
  `ID_empleado` INT NOT NULL,
  `historial_entrenamiento` VARCHAR(45) NULL,
  `area_especializacion` VARCHAR(45) NULL,
  `horario_inicio_entrenamiento` DATETIME NULL,
  `horario_fin_entrenamiento` DATETIME NULL,
  `plan_entrenamiento` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_empleado`),
  CONSTRAINT `fk_Entrenadores_1`
    FOREIGN KEY (`ID_empleado`)
    REFERENCES `mydb`.`Empleados` (`ID_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguridad` (
  `ID_empleado` INT NOT NULL,
  `cod_licencia` INT NULL,
  `historial_servicio` VARCHAR(255) NULL,
  `horario_inicio_rondas` DATETIME NULL,
  `horario_fin_rondas` DATETIME NULL,
  PRIMARY KEY (`ID_empleado`),
  CONSTRAINT `fk_Seguridad_1`
    FOREIGN KEY (`ID_empleado`)
    REFERENCES `mydb`.`Empleados` (`ID_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal Administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal Administrativo` (
  `ID_empleado` INT NOT NULL,
  `historia_laboral` VARCHAR(255) NULL,
  `info_fiscal` VARCHAR(255) NULL,
  `titulo` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_empleado`),
  CONSTRAINT `fk_Personal Administrativo_1`
    FOREIGN KEY (`ID_empleado`)
    REFERENCES `mydb`.`Empleados` (`ID_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal Medico` (
  `ID_empleado` INT NOT NULL,
  `cod_tarjeta_profesional` INT NULL,
  `horario_inicio_consulta` DATETIME NULL,
  `horario_fin_consulta` DATETIME NULL,
  `experiencia` VARCHAR(255) NULL,
  `especialidad` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_empleado`),
  CONSTRAINT `fk_Personal Medico_1`
    FOREIGN KEY (`ID_empleado`)
    REFERENCES `mydb`.`Empleados` (`ID_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
